package GUI;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.ChartPanel;
import BLL.thongKeSanPhamBLL;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.labels.CategoryItemLabelGenerator;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;

/**
 *
 * @author loc01
 */
public class thongKeSanPhamGUI extends javax.swing.JPanel {
    public thongKeSanPhamBLL tkSanPhamBLL;
    /**
     * Creates new form thongKeGUI
     */
    public thongKeSanPhamGUI() {
        initComponents();
        tkSanPhamBLL = new thongKeSanPhamBLL();
        buttonchitiet();
        Timkiem();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(1100, 650));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel16.setText("CHI TIẾT THỐNG KÊ SẢN PHẨM");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "HÃNG", "SỐ LƯỢNG"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("TỪ NGÀY:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("ĐẾN NGÀY:");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("TÌM KIẾM");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo ngày", "Theo tháng", "Theo năm" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jLabel2.setText("Tuần");

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jLabel3.setText("Tháng ");

        jPanel8.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jLabel15.setText("Năm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("OPPO:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("XIAOMI:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("SAMSUNG:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("IPHONE:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("NOKIA:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(35, 134, 54));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Chi tiết thống kê");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonchitiet(){
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                // Đặt jDialog1 thành cửa sổ modal
                jDialog1.setModal(true);

                // Đặt vị trí của JDialog ở giữa màn hình
                jDialog1.setLocationRelativeTo(null);

                // Hiển thị jDialog1
                jDialog1.setVisible(true);
            }
        });
    }
    
    private void Timkiem(){
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                if (jDateChooser1.getDate() != null && jDateChooser2.getDate() != null) {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

                    String ngayBatDau = sdf.format(jDateChooser2.getDate());
                    String ngayKetThuc = sdf.format(jDateChooser1.getDate());
                    // Gọi BLL để thực hiện truy vấn
                    List<String[]> result = tkSanPhamBLL.thongKeSanPham(ngayBatDau, ngayKetThuc);
                    // Hiển thị kết quả trên jTable1
                    DefaultTableModel model = new DefaultTableModel();
                    model.addColumn("Tên SP");
                    model.addColumn("Tổng Số Lượng");

                    for (String[] row : result) {
                        model.addRow(row);
                    }
                    jTable1.setModel(model);
                }
                else{
                    JOptionPane.showMessageDialog(thongKeSanPhamGUI.this, "Vui lòng nhập đầy đủ thông tin", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedOption = jComboBox1.getSelectedItem().toString();

        if ("Theo ngày".equals(selectedOption)) {
            createPieChartBasedOnDay();
        }
//        else if ("Theo tuần".equals(selectedOption)) {
//            createPieChartBasedOnWeek();
//        } 
        else if ("Theo tháng".equals(selectedOption)) {
            createPieChartBasedOnMonth();
        } else if ("Theo năm".equals(selectedOption)) {
            createPieChartBasedOnYear();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    private void createPieChartBasedOnDay() {
        updateLabelsNgay();
        createPieChart();
        createBarChart();
    }

//    private void createPieChartBasedOnWeek() {
//        updateLabelsTuan();
//        createPieChart();
//    }

    private void createPieChartBasedOnMonth() {
        updateLabelsThang();
        createPieChart();
        createBarChartMonth();
    }
    
    private void createPieChartBasedOnYear() {
        updateLabelsNam();
        createPieChart();
        createBarChartYear();
    }    
    
    private void createPieChart() {
        String soluongsamsung = jLabel5.getText();
        String soluongoppo = jLabel11.getText();
        String soluongiphone = jLabel12.getText();
        String soluongxioami = jLabel13.getText();
        String soluongnokia = jLabel14.getText();
                                
        DefaultPieDataset dataset = new DefaultPieDataset();
        // Chuyển đổi chuỗi thành số nguyên
        int samsungCount = Integer.parseInt(soluongsamsung);
        int oppoCount = Integer.parseInt(soluongoppo);
        int iphoneCount = Integer.parseInt(soluongiphone);
        int xiaomiCount = Integer.parseInt(soluongxioami);
        int nokiaCount = Integer.parseInt(soluongnokia);

        // Thêm dữ liệu đã chuyển đổi vào dataset
        dataset.setValue("Samsung", samsungCount);
        dataset.setValue("Oppo", oppoCount);
        dataset.setValue("Iphone", iphoneCount);
        dataset.setValue("Xiaomi", xiaomiCount);
        dataset.setValue("Nokia", nokiaCount);

        JFreeChart chart = ChartFactory.createPieChart(
                "Số lượng sản phẩm theo dòng điện thoại", // Tiêu đề của biểu đồ
                dataset,          // Dữ liệu cho biểu đồ
        true, true, true);

        PiePlot plot = (PiePlot) chart.getPlot();
        
        ChartPanel cpanel = new ChartPanel(chart);
        cpanel.setSize(300, 300);
        jPanel1.removeAll();
        jPanel1.add(cpanel, BorderLayout.CENTER);       
        jPanel1.revalidate();
    }
    
    private void createBarChart() {
        thongKeSanPhamBLL bll = new thongKeSanPhamBLL();
        List<String[]> salesData = bll.getSalesDataForWeek();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (String[] data : salesData) {
            String ngayTrongTuan = data[0];
            int tongSoLuong = Integer.parseInt(data[1]);
            String category = ngayTrongTuan; // Sử dụng ngày làm category
            Color color = Color.RED; // Mặc định màu đỏ cho tất cả các ngày

            dataset.addValue(tongSoLuong, "Số lượng", category);
        }

        JFreeChart barChart = ChartFactory.createBarChart(
            "Số lượng sản phẩm theo ngày trong tuần",
            "Ngày",
            "Số lượng",
            dataset,
            PlotOrientation.VERTICAL,
            true, true, false);

        CategoryPlot plot = barChart.getCategoryPlot();

        BarRenderer renderer = (BarRenderer) plot.getRenderer();

        // Đặt màu cho từng cột
        for (int i = 0; i < salesData.size(); i++) {
            Color color = Color.RED; // Mặc định màu đỏ
            renderer.setSeriesPaint(i, color);
        }

        // Hiển thị số lượng trên đỉnh mỗi cột
        CategoryItemLabelGenerator generator = new StandardCategoryItemLabelGenerator("{2}", new DecimalFormat("0"));
        renderer.setBaseItemLabelGenerator(generator);
        renderer.setBaseItemLabelsVisible(true);

        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setSize(300, 300);
        jPanel6.removeAll();
        jPanel6.add(chartPanel, BorderLayout.CENTER);
        jPanel6.revalidate();
    }


    private void createBarChartMonth() {
        thongKeSanPhamBLL bll = new thongKeSanPhamBLL();
        List<String[]> salesData = bll.getRecentMonthsSalesData();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (String[] data : salesData) {
            String monthName = data[0];
            int tongSoLuong = Integer.parseInt(data[1]);
            String category;
            Color color;

            // Xác định màu cho cột cuối cùng (tháng hiện tại)
            if (monthName.equals("Tháng hiện tại")) {
                category = "Category 1";
                color = Color.GREEN;
            } else {
                category = "Các tháng";
                color = Color.YELLOW;
            }

            dataset.addValue(tongSoLuong, category, monthName);
        }

        JFreeChart barChart = ChartFactory.createBarChart(
            "Tổng số lượng sản phẩm bán trong các tháng gần đây",
            "Category",
            "Value",
            dataset,
            PlotOrientation.VERTICAL,
            true, true, false);

        CategoryPlot plot = barChart.getCategoryPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();

        // Đặt màu cho cột
        for (int i = 0; i < salesData.size(); i++) {
            String monthName = salesData.get(i)[0];
            Color color = monthName.equals("Tháng hiện tại") ? Color.GREEN : Color.YELLOW;
            renderer.setSeriesPaint(i, color);
        }

        // Hiển thị số lượng trên đầu mỗi cột
        CategoryItemLabelGenerator generator = new StandardCategoryItemLabelGenerator("{2}", new DecimalFormat("0"));
        renderer.setBaseItemLabelGenerator(generator);
        renderer.setBaseItemLabelsVisible(true);

        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setSize(300, 300);
        jPanel6.removeAll();
        jPanel6.add(chartPanel, BorderLayout.CENTER);
        jPanel6.revalidate();
    }
    
    private void createBarChartYear() {
        thongKeSanPhamBLL bll = new thongKeSanPhamBLL();
        List<String[]> salesData = bll.getRecentYearsSalesData();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (String[] data : salesData) {
            String yearName = data[0];
            int tongSoLuong = Integer.parseInt(data[1]);
            String category;
            Color color;

            // Xác định màu cho cột cuối cùng (năm hiện tại)
            if (yearName.equals(Integer.toString(Calendar.getInstance().get(Calendar.YEAR)))) {
                category = "Năm nay";
                color = Color.BLUE;
            } else {
                category = "Các năm";
                color = Color.BLUE;
            }

            dataset.addValue(tongSoLuong, category, yearName);
        }

        JFreeChart barChart = ChartFactory.createBarChart(
            "Tổng số lượng sản phẩm bán trong các năm gần đây",
            "Category",
            "Value",
            dataset,
            PlotOrientation.VERTICAL,
            true, true, false);

        CategoryPlot plot = barChart.getCategoryPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();

        // Đặt màu cho cột
        for (int i = 0; i < salesData.size(); i++) {
            String yearName = salesData.get(i)[0];
            Color color = yearName.equals(Integer.toString(Calendar.getInstance().get(Calendar.YEAR))) ? Color.BLUE : Color.BLUE;
            renderer.setSeriesPaint(i, color);
        }

        // Hiển thị số lượng trên đầu mỗi cột
        CategoryItemLabelGenerator generator = new StandardCategoryItemLabelGenerator("{2}", new DecimalFormat("0"));
        renderer.setBaseItemLabelGenerator(generator);
        renderer.setBaseItemLabelsVisible(true);

        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setSize(300, 300);
        jPanel6.removeAll();
        jPanel6.add(chartPanel, BorderLayout.CENTER);
        jPanel6.revalidate();
    }

    private void updateLabelsNgay() {
        // Lấy dữ liệu tổng số lượng sản phẩm của từng hãng từ cơ sở dữ liệu
        int samsungCount = tkSanPhamBLL.getSanPhamCountByHang("Samsung");
        int oppoCount = tkSanPhamBLL.getSanPhamCountByHang("Oppo");
        int iphoneCount = tkSanPhamBLL.getSanPhamCountByHang("Iphone");
        int xiaomiCount = tkSanPhamBLL.getSanPhamCountByHang("Xiaomi");
        int nokiaCount = tkSanPhamBLL.getSanPhamCountByHang("Nokia");

        // Cập nhật các JLabel để hiển thị dữ liệu
        jLabel5.setText(String.valueOf(samsungCount));
        jLabel11.setText(String.valueOf(oppoCount));
        jLabel12.setText(String.valueOf(iphoneCount));
        jLabel13.setText(String.valueOf(xiaomiCount));
        jLabel14.setText(String.valueOf(nokiaCount));
    }
    
//    private void updateLabelsTuan() {
//        // Lấy dữ liệu tổng số lượng sản phẩm của từng hãng từ cơ sở dữ liệu
//        int samsungCount = tkSanPhamBLL.getSanPhamCountByHangForWeek("Samsung");
//        int oppoCount = tkSanPhamBLL.getSanPhamCountByHangForWeek("Oppo");
//        int iphoneCount = tkSanPhamBLL.getSanPhamCountByHangForWeek("Iphone");
//        int xiaomiCount = tkSanPhamBLL.getSanPhamCountByHangForWeek("Xiaomi");
//        int nokiaCount = tkSanPhamBLL.getSanPhamCountByHangForWeek("Nokia");
//
//        // Cập nhật các JLabel để hiển thị dữ liệu
//        jLabel5.setText(String.valueOf(samsungCount));
//        jLabel11.setText(String.valueOf(oppoCount));
//        jLabel12.setText(String.valueOf(iphoneCount));
//        jLabel13.setText(String.valueOf(xiaomiCount));
//        jLabel14.setText(String.valueOf(nokiaCount));
//    }
    
    private void updateLabelsNam() {
        // Lấy dữ liệu tổng số lượng sản phẩm của từng hãng từ cơ sở dữ liệu
        int samsungCount = tkSanPhamBLL.getSanPhamCountByHangForYear("Samsung");
        int oppoCount = tkSanPhamBLL.getSanPhamCountByHangForYear("Oppo");
        int iphoneCount = tkSanPhamBLL.getSanPhamCountByHangForYear("Iphone");
        int xiaomiCount = tkSanPhamBLL.getSanPhamCountByHangForYear("Xiaomi");
        int nokiaCount = tkSanPhamBLL.getSanPhamCountByHangForYear("Nokia");

        // Cập nhật các JLabel để hiển thị dữ liệu
        jLabel5.setText(String.valueOf(samsungCount));
        jLabel11.setText(String.valueOf(oppoCount));
        jLabel12.setText(String.valueOf(iphoneCount));
        jLabel13.setText(String.valueOf(xiaomiCount));
        jLabel14.setText(String.valueOf(nokiaCount));
    }
    
    private void updateLabelsThang() {
        // Lấy dữ liệu tổng số lượng sản phẩm của từng hãng từ cơ sở dữ liệu
        int samsungCount = tkSanPhamBLL.getSanPhamCountByHangForMonth("Samsung");
        int oppoCount = tkSanPhamBLL.getSanPhamCountByHangForMonth("Oppo");
        int iphoneCount = tkSanPhamBLL.getSanPhamCountByHangForMonth("Iphone");
        int xiaomiCount = tkSanPhamBLL.getSanPhamCountByHangForMonth("Xiaomi");
        int nokiaCount = tkSanPhamBLL.getSanPhamCountByHangForMonth("Nokia");

        // Cập nhật các JLabel để hiển thị dữ liệu
        jLabel5.setText(String.valueOf(samsungCount));
        jLabel11.setText(String.valueOf(oppoCount));
        jLabel12.setText(String.valueOf(iphoneCount));
        jLabel13.setText(String.valueOf(xiaomiCount));
        jLabel14.setText(String.valueOf(nokiaCount));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
